### assumes ubuntu image
---
- name: update apt cache
  apt: update_cache=yes
  become: true

- name: install packages
  apt: 
      pkg: 
          - curl
          - build-essential
          - git
          - pkg-config
          - default-jre
          - unzip
      state: latest
  become: true

- name: install nextflow
  include_tasks: nextflow.yml

- name: install docker
  include_tasks: docker.yml

- name: install singularity
  include_tasks: singularity.yml

- name: install miniconda
  include_tasks: conda.yml